### ISSUE TITLE
Underflow error in StakingPoolV2.getUserReward(alice, 1) 

### ISSUE THREAD

**Issue by qpzm** [elysia-dev/elyfi-stakingpool-v2#3]
## Problem
`StakingPoolV2.getUserReward(alice, 1)` raises an underflow error after alice migrates all from round 1 to round 2 and totalPrincipal of round 1 goes down to 0.

I added a failing test here: https://github.com/elysia-dev/elyfi-stakingpool-v2/tree/fix/last-migrate-all.

```sh
$ yarn hardhat test test/migrate.test.ts

1) StakingPool.migrate
       second round initiated
         success when the last user migrate all:
     Error: VM Exception while processing transaction: reverted with panic code 0x11 (Arithmetic operation underflowed or overflowed outside of an unchecked block)
      at StakingPoolV2.getUserReward (contracts/logic/StakingPoolLogicV2.sol:45)
      at StakingPoolV2.getUserReward (contracts/StakingPoolV2.sol:59)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at runNextTicks (internal/process/task_queues.js:64:3)
      at listOnTimeout (internal/timers.js:526:9)
      at processTimers (internal/timers.js:500:7)
      at HardhatNode.runCall (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:503:20)
      at EthModule._callAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:9)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:108:18)
```

## Cause
This is because `migrate` does not update the pool index which the user migrates from, namely round 1 in this case.
https://github.com/elysia-dev/elyfi-stakingpool-v2/blob/5922029b4d719e8aaba90c05b70b8b484fe576c2/contracts/StakingPoolV2.sol#L177

**Comment by qpzm** [comment]
After 2022-04-18, we delete the concept of a staking round. So, there is no need to fix.
